version: '3.9'

services:
  bot:
    build:
        context: .
        dockerfile: Dockerfile  
    environment:
      DISCORD_PROD_TOKEN: "YOUR_KEY"
      HOLODEX_API_KEY: "YOUR_KEY"
      MONGODB_URL: "mongodb://db/luna"
      GUILD_ID: "YOUR_GUILD_ID"
      CLIENT_ID: "YOUR_APPLICATION_ID"
    depends_on:
      - db
  db:
    image: mongo:5
    volumes:
      - ./data/mongo:/data/db
